POST http://localhost:8080/events
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ0MTc1NTc5LCJ1c2VySWQiOjF9.0IHH--YasHd6NQMnkBchASewA5AwKA8ybuEni2uEW2k

{
  "name": "Interview process",
  "description": "Be at miss or each good play home they. It leave taste mr in it fancy. She son lose does fond bred gave lady get. Sir her company conduct expense bed any. Sister depend change off piqued one. Contented continued any happiness instantly objection yet her allowance. Use correct day new brought tedious. By come this been in. Kept easy or sons my it done.",
  "location": "San Francisco",
  "dateTime": "2025-01-01T15:30:00.000Z"
}